src/ETFRank/CandidateBundle/Entity/Candidate.php
<?php

namespace ETFRank\CandidateBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Candidate
 *
 * @ORM\Table("candidate")
 * @ORM\Entity
 */
class Candidate
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var CandidateGroup
     *
     * @ORM\ManyToOne(targetEntity="CandidateGroup", inversedBy="candidates")
     * @ORM\JoinColumn(name="group_id", referencedColumnName="id", onDelete="CASCADE", nullable=false)
     */
    private $group;

    /**
     * @var integer
     *
     * @ORM\Column(name="personal_id", type="integer", nullable=true)
     */
    private $personalId;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=150, nullable=true)
     * @Assert\NotBlank()
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="parent_name", type="string", length=80, nullable=true)
     * @Assert\NotBlank()
     */
    private $parentName;

    /**
     * @var string
     *
     * @ORM\Column(name="high_school", type="string", length=250, nullable=true)
     * @Assert\NotBlank()
     */
    private $highSchool;

    /**
     * @var string
     *
     * @ORM\Column(name="high_school_score", type="decimal", scale=2, nullable=true)
     * @Assert\NotBlank()
     * @Assert\Type("numeric")
     * @Assert\Range(min="0", max="40")
     */
    private $highSchoolScore;

    /**
     * @var boolean
     *
     * @ORM\Column(name="award_mathematics", type="boolean", nullable=true)
     */
    private $awardMathematics;

    /**
     * @var boolean
     *
     * @ORM\Column(name="award_physics", type="boolean", nullable=true)
     */
    private $awardPhysics;

    /**
     * @var boolean
     *
     * @ORM\Column(name="award_informatics", type="boolean", nullable=true)
     */
    private $awardInformatics;

    /**
     * @var boolean
     *
     * @ORM\Column(name="subscribed_for_mathematics", type="boolean", nullable=true)
     */
    private $subscribedForMathematics;

    /**
     * @var boolean
     *
     * @ORM\Column(name="subscribed_for_physics", type="boolean", nullable=true)
     */
    private $subscribedForPhysics;

    /**
     * @var string
     *
     * @ORM\Column(name="entrance_exam_mathematics", type="decimal", scale=2, nullable=true)
     * @Assert\Type("numeric")
     * @Assert\Range(min="0", max="100")
     */
    private $entranceExamMathematics;

    /**
     * @var string
     *
     * @ORM\Column(name="entrance_exam_physics", type="decimal", scale=2, nullable=true)
     * @Assert\Type("numeric")
     * @Assert\Range(min="0", max="100")
     */
    private $entranceExamPhysics;

    /**
     * @var int
     *
     * @ORM\Column(name="chosen_field_of_study", type="smallint", nullable=true)
     * @Assert\NotBlank()
     */
    private $chosenFieldOfStudy;

    const FIELD_OF_STUDY_ER = 1;
    const FIELD_OF_STUDY_SI = 2;

    /**
     * @var boolean
     *
     * @ORM\Column(name="confirmed", type="boolean")
     */
    private $confirmed = false;

    /**
     * @var DesiredFieldOfStudy
     *
     * @ORM\OneToOne(targetEntity="DesiredFieldOfStudy", mappedBy="candidate")
     **/
    private $desiredFieldOfStudy;

    /**
     * @var DesiredDepartment
     *
     * @ORM\OneToOne(targetEntity="DesiredDepartment", mappedBy="candidate")
     **/
    private $desiredDepartment;

    /**
     * @var CandidateRank
     *
     * @ORM\OneToOne(targetEntity="CandidateRank", mappedBy="candidate")
     **/
    private $rank;


    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return CandidateGroup
     */
    public function getGroup()
    {
        return $this->group;
    }

    /**
     * @param CandidateGroup $group
     *
     * @return self
     */
    public function setGroup(CandidateGroup $group)
    {
        $this->group = $group;

        return $this;
    }

    /**
     * @return int
     */
    public function getPersonalId()
    {
        return $this->personalId;
    }

    /**
     * @param int $personalId
     *
     * @return self
     */
    public function setPersonalId($personalId)
    {
        $this->personalId = $personalId;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return self
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get parentName
     *
     * @return string
     */
    public function getParentName()
    {
        return $this->parentName;
    }

    /**
     * Set parentName
     *
     * @param string $parentName
     *
     * @return self
     */
    public function setParentName($parentName)
    {
        $this->parentName = $parentName;

        return $this;
    }

    /**
     * @return boolean
     */
    public function isAwardInformatics()
    {
        return $this->awardInformatics;
    }

    /**
     * @param boolean $awardInformatics
     *
     * @return self
     */
    public function setAwardInformatics($awardInformatics)
    {
        $this->awardInformatics = $awardInformatics;

        return $this;
    }

    /**
     * @return boolean
     */
    public function isAwardMathematics()
    {
        return $this->awardMathematics;
    }

    /**
     * @param boolean $awardMathematics
     *
     * @return self
     */
    public function setAwardMathematics($awardMathematics)
    {
        $this->awardMathematics = $awardMathematics;

        return $this;
    }

    /**
     * @return boolean
     */
    public function isAwardPhysics()
    {
        return $this->awardPhysics;
    }

    /**
     * @param boolean $awardPhysics
     *
     * @return self
     */
    public function setAwardPhysics($awardPhysics)
    {
        $this->awardPhysics = $awardPhysics;

        return $this;
    }

    public function getAwards()
    {
        $awards = array();
        if ($this->isAwardMathematics()) {
            $awards[] = 'Mathematics';
        }
        if ($this->isAwardPhysics()) {
            $awards[] = 'Physics';
        }
        if ($this->isAwardInformatics()) {
            $awards[] = 'Informatics';
        }

        return implode(', ', $awards);
    }

    /**
     * @return int
     */
    public function getChosenFieldOfStudy()
    {
        return $this->chosenFieldOfStudy;
    }

    /**
     * @param int $chosenFieldOfStudy
     *
     * @return self
     */
    public function setChosenFieldOfStudy($chosenFieldOfStudy)
    {
        $this->chosenFieldOfStudy = $chosenFieldOfStudy;

        return $this;
    }

    static public function getFieldsOfStudy()
    {
        return array(
            self::FIELD_OF_STUDY_ER => 'ER',
            self::FIELD_OF_STUDY_SI => 'SI',
        );
    }

    public function getHumanReadableChosenFieldOfStudy()
    {
        if (isset($this->getFieldsOfStudy()[$this->chosenFieldOfStudy])) {
            return $this->getFieldsOfStudy()[$this->chosenFieldOfStudy];
        } else {
            return '';
        }
    }

    /**
     * @return boolean
     */
    public function isConfirmed()
    {
        return $this->confirmed;
    }

    /**
     * @param boolean $confirmed
     *
     * @return self
     */
    public function setConfirmed($confirmed)
    {
        $this->confirmed = $confirmed;

        return $this;
    }

    /**
     * @return boolean
     */
    public function isSubscribedForMathematics()
    {
        return $this->subscribedForMathematics;
    }

    /**
     * @param boolean $subscribedForMathematics
     *
     * @return self
     */
    public function setSubscribedForMathematics($subscribedForMathematics)
    {
        $this->subscribedForMathematics = $subscribedForMathematics;

        return $this;
    }

    /**
     * @return boolean
     */
    public function isSubscribedForPhysics()
    {
        return $this->subscribedForPhysics;
    }

    /**
     * @param boolean $subscribedForPhysics
     *
     * @return self
     */
    public function setSubscribedForPhysics($subscribedForPhysics)
    {
        $this->subscribedForPhysics = $subscribedForPhysics;

        return $this;
    }

    /**
     * @return string
     */
    public function getEntranceExamMathematics()
    {
        return $this->entranceExamMathematics;
    }

    /**
     * @param string $entranceExamMathematics
     *
     * @return self
     */
    public function setEntranceExamMathematics($entranceExamMathematics)
    {
        $this->entranceExamMathematics = $entranceExamMathematics;

        return $this;
    }

    /**
     * @return string
     */
    public function getEntranceExamPhysics()
    {
        return $this->entranceExamPhysics;
    }

    /**
     * @param string $entranceExamPhysics
     *
     * @return self
     */
    public function setEntranceExamPhysics($entranceExamPhysics)
    {
        $this->entranceExamPhysics = $entranceExamPhysics;

        return $this;
    }

    /**
     * @return string
     */
    public function getHighSchool()
    {
        return $this->highSchool;
    }

    /**
     * @param string $highSchool
     *
     * @return self
     */
    public function setHighSchool($highSchool)
    {
        $this->highSchool = $highSchool;

        return $this;
    }

    /**
     * @return string
     */
    public function getHighSchoolScore()
    {
        return $this->highSchoolScore;
    }

    /**
     * @param string $highSchoolScore
     *
     * @return self
     */
    public function setHighSchoolScore($highSchoolScore)
    {
        $this->highSchoolScore = $highSchoolScore;

        return $this;
    }

    /**

src/ETFRank/CandidateBundle/Controller/GroupController.php
<?php

namespace ETFRank\CandidateBundle\Controller;

use Doctrine\ORM\EntityManager;
use ETFRank\CandidateBundle\Entity\CandidateGroup;
use ETFRank\CandidateBundle\Form\CandidateGroupType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/group")
 */
class GroupController extends CRUDController
{
    /**
     * List all groups.
     *
     * @Route("/list", name="group_list")
     */
    public function listGroupsAction()
    {
        return $this->listAction(
            'ETFRankCandidateBundle:CandidateGroup',
            'ETFRankCandidateBundle:Group:list.html.twig',
            'All Groups',
            array(),
            array('name' => 'ASC')
        );
    }

    /**
     * Create new candidate group.
     *
     * @Route("/create", name="group_create")
     */
    public function createGroupAction(Request $request)
    {
        $group = new CandidateGroup();
        $formType = new CandidateGroupType();
        $redirect = $this->generateUrl('homepage');

        return $this->createAction(
            $request,
            $group,
            $formType,
            $redirect,
            'Group saved successfully',
            array('pageName' => 'Create new group')
        );
    }

    /**
     * Update candidate group.
     *
     * @Route("/update/{group}", name="group_update")
     */
    public function updateGroupAction(Request $request, CandidateGroup $group)
    {
        $formType = new CandidateGroupType();
        $redirect = $this->generateUrl('homepage');

        return $this->updateAction(
            $request,
            $group,
            $formType,
            $redirect,
            'Group saved successfully',
            array('pageName' => "Update group '{$group->getName()}'")
        );
    }

    /**
     * Remove candidate group.
     *
     * @Route("/remove/{group}", name="group_remove")
     */
    public function removeGroupAction(Request $request, CandidateGroup $group)
    {
        $redirect = $this->generateUrl('homepage');

        return $this->removeAction(
            $request,
            $group,
            $redirect,
            'Confirm deletion of this group.',
            'Group removed successfully',
            array('pageName' => "Remove group '{$group->getName()}'")
        );
    }

    /**
     * List all candidates from group.
     *
     * @Route("/view/{group}", name="group_view")
     */
    public function listCandidatesAction(Request $request, CandidateGroup $group)
    {
        /** @var EntityManager $em */
        $em = $this->getDoctrine()->getManager();
        $queryBuilder = $em->getRepository('ETFRankCandidateBundle:Candidate')
            ->createQueryBuilder('e')
            ->where('e.group = :group')
            ->setParameter('group', $group->getId());

        return $this->listPaginatedFromQueryBuilderAction(
            $queryBuilder,
            $request->query->get('page', 1),
            1500,
            'ETFRankCandidateBundle:Group:listCandidates.html.twig',
            array(
                'pageName' => "Candidates from group '{$group->getName()}'",
                'group'    => $group,
            )
        );
    }
}

src/ETFRank/CandidateBundle/Resources/views/Group/list.html.twig
<table class="table">
    {% for group in entities %}
    <tr>
        <td>
            <a href="{{ path('group_view', {'group': group.id}) }}">
                {{ group.name }}
            </a>
        </td>
        <td class="text-right" style="padding-right:0">
            <div class="btn-group">
                <a href="{{ path('group_update', {'group': group.id}) }}" class="btn btn-warning btn-sm" title="Edit">
                    <span class="glyphicon glyphicon-pencil"></span>
                </a>
                <a href="{{ path('group_remove', {'group': group.id}) }}" class="btn btn-danger btn-sm" title="Remove">
                    <span class="glyphicon glyphicon-remove"></span>
                </a>
            </div>

            <div class="btn-group">
                <a href="{{ path('rank_list_list', {'group': group.id}) }}" class="btn btn-default btn-sm" title="Rank lists">
                    <span class="glyphicon glyphicon-list"></span>
                </a>
                <a href="{{ path('simulation_run', {'group': group.id}) }}" class="btn btn-default btn-sm" title="Simulations">
                    <span class="glyphicon glyphicon-tasks"></span>
                </a>
            </div>
        </td>
    </tr>
    {% endfor %}
</table>

src/ETFRank/CandidateBundle/Resources/views/Group/listCandidates.html.twig
{% extends 'ETFRankCandidateBundle::layout.html.twig' %}

{% block page_header %}{{ pageName }}{% endblock %}

{% block content %}
    <div>Count: {{ pagination.count }}</div>
    <div class="text-right">
        <a href="{{ path('manual_entry_create', {'group': group.id}) }}" class="btn btn-success">Add new candidate</a>
        <a href="{{ path('crawler_run', {'group': group.id}) }}" class="btn btn-success">Run crawler</a>
        <a href="{{ path('import_csv_run', {'group': group.id}) }}" class="btn btn-success">Import CSV</a>
    </div>
    <table class="table">
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>HS Score</th>
            <th>Awards</th>
            <th>FoS</th>
            <th>EE Mathematics</th>
            <th>EE Physics</th>
            <th>ER Score</th>
            <th>SI Score</th>
            <th></th>
        </tr>

        {% for candidate in pagination %}
            <tr>
                <td>{{ candidate.personalId }}</td>
                <td>{{ candidate.name }}</td>
                <td>{{ candidate.highSchoolScore }}</td>
                <td>{{ candidate.awards }}</td>
                <td>{{ candidate.humanReadableChosenFieldOfStudy }}</td>
                <td>{{ candidate.entranceExamMathematics }}</td>
                <td>{{ candidate.entranceExamPhysics }}</td>
                <td>{{ candidate.ERScore|number_format(2) }}</td>
                <td>{{ candidate.SIScore|number_format(2) }}</td>
                <td class="text-right">
                    <div class="btn-group">
                        {% if not candidate.confirmed %}
                            <a href="{{ path('manual_entry_confirm', {'candidate': candidate.id}) }}" class="btn btn-info btn-sm">
                                <span class="glyphicon glyphicon-ok"></span>
                            </a>
                        {% endif %}
                        <a href="{{ path('manual_entry_update', {'candidate': candidate.id}) }}" class="btn btn-warning btn-sm">
                            <span class="glyphicon glyphicon-pencil"></span>
                        </a>
                        <a href="{{ path('manual_entry_remove', {'candidate': candidate.id}) }}" class="btn btn-danger btn-sm">
                            <span class="glyphicon glyphicon-remove"></span>
                        </a>
                    </div>
                </td>
            </tr>
        {% endfor %}
    </table>

    {{ knp_pagination_render(pagination) }}
{% endblock %}